In [6]:
import pandas as pd
import numpy as np

daily = pd.read_csv("FRED/Daily.csv")
daily_7 = pd.read_csv("FRED/Daily_7_Day.csv")
daily_close = pd.read_csv("FRED/Daily_Close.csv")

In [7]:
daily.columns = ['Date', 'DGS1', 'DGS10', 'T10Y2Y', 'DBAA', 'USD1MTD156N', 'DCOILBRENTEU', 'DTWEXB', 'DEXUSEU', 'T10YIE', 'T5YIFR']
daily_7.columns = ['Date', 'DFF']
daily_close.columns = ['Date', 'BAMLH0A0HYM2EY']

In [ ]:
temp = pd.merge(daily, daily_7, on='Date', how='outer')
result = pd.merge(temp, daily_close, on='Date', how='outer')

In [33]:
dates = []

if result['Date'][0] != '1/2/62':
    for date in result['Date']:
        parts = date.split('-')
        print(parts)
        month = parts[1]
        if month[0] == '0':
            month = month[1]
        day = parts[2]
        if day[0] == '0':
            day = day[1]
        year = parts[0][2:]
        dates.append(month+'/'+day+'/'+year)
    
    result['Date'] = dates

          Date   DGS1 DGS10 T10Y2Y DBAA USD1MTD156N DCOILBRENTEU DTWEXB  \
0       1/2/62   3.22  4.06      .    .           .            .      .
1       1/3/62   3.24  4.03      .    .           .            .      .
2       1/4/62   3.24  3.99      .    .           .            .      .
3       1/5/62   3.26  4.02      .    .           .            .      .
4       1/8/62   3.31  4.03      .    .           .            .      .
5       1/9/62   3.32  4.05      .    .           .            .      .
6      1/10/62   3.33  4.07      .    .           .            .      .
7      1/11/62   3.33  4.08      .    .           .            .      .
8      1/12/62   3.30  4.08      .    .           .            .      .
9      1/15/62   3.32  4.10      .    .           .            .      .
10     1/16/62   3.30  4.13      .    .           .            .      .
11     1/17/62   3.30  4.12      .    .           .            .      .
12     1/18/62   3.27  4.11      .    .           .            .      .
13     1/19/62   3.27  4.11      .    .           .            .      .
14     1/22/62   3.25  4.09      .    .           .            .      .
15     1/23/62   3.25  4.11      .    .           .            .      .
16     1/24/62   3.24  4.10      .    .           .            .      .
17     1/25/62   3.27  4.11      .    .           .            .      .
18     1/26/62   3.28  4.11      .    .           .            .      .
19     1/29/62   3.28  4.12      .    .           .            .      .
20     1/30/62   3.28  4.11      .    .           .            .      .
21     1/31/62   3.29  4.10      .    .           .            .      .
22      2/1/62  3.300  4.09      .    .           .            .      .
23      2/2/62  3.300  4.08      .    .           .            .      .
24      2/5/62  3.290  4.07      .    .           .            .      .
25      2/6/62  3.290  4.06      .    .           .            .      .
26      2/7/62  3.290  4.07      .    .           .            .      .
27      2/8/62  3.300  4.07      .    .           .            .      .
28      2/9/62  3.280  4.05      .    .           .            .      .
29     2/12/62      .     .      .    .           .            .      .
...        ...    ...   ...    ...  ...         ...          ...    ...
23425   6/9/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23426  6/10/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23427  6/16/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23428  6/17/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23429  6/23/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23430  6/24/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23431  6/30/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23432   7/1/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23433   7/7/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23434   7/8/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23435  7/14/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23436  7/15/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23437  7/21/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23438  7/22/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23439  7/28/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23440  7/29/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23441   8/4/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23442   8/5/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23443  8/11/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23444  8/12/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23445  8/18/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23446  8/19/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23447  8/25/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23448  8/26/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23449   9/1/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23450   9/2/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23451   9/8/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23452   9/9/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23453  9/15/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN
23454  9/16/18    NaN   NaN    NaN  NaN         NaN          NaN    NaN

      DEXUSEU T10YIE T5YIFR   DFF BAMLH0A0HYM2EY
0           .      .      .  2.75            NaN
1           .      .      .  2.50            NaN
2           .      .      .  2.75            NaN
3           .      .      .  2.50            NaN
4           .      .      .  2.00            NaN
5           .      .      .  1.25            NaN
6           .      .      .  0.50            NaN
7           .      .      .  2.75            NaN
8           .      .      .  2.75            NaN
9           .      .      .  3.00            NaN
10          .      .      .  2.50            NaN
11          .      .      .  3.00            NaN
12          .      .      .  2.25            NaN
13          .      .      .  2.00            NaN
14          .      .      .  1.25            NaN
15          .      .      .  0.50            NaN
16          .      .      .  0.25            NaN
17          .      .      .  2.00            NaN
18          .      .      .  2.50            NaN
19          .      .      .  2.50            NaN
20          .      .      .  1.50            NaN
21          .      .      .  1.50            NaN
22          .      .      .  2.25            NaN
23          .      .      .  1.50            NaN
24          .      .      .  2.00            NaN
25          .      .      .  2.75            NaN
26          .      .      .  2.75            NaN
27          .      .      .  2.75            NaN
28          .      .      .  2.75            NaN
29          .      .      .  2.75            NaN
...       ...    ...    ...   ...            ...
23425     NaN    NaN    NaN  1.70            NaN
23426     NaN    NaN    NaN  1.70            NaN
23427     NaN    NaN    NaN  1.90            NaN
23428     NaN    NaN    NaN  1.90            NaN
23429     NaN    NaN    NaN  1.92            NaN
23430     NaN    NaN    NaN  1.92            NaN
23431     NaN    NaN    NaN  1.91           6.44
23432     NaN    NaN    NaN  1.91            NaN
23433     NaN    NaN    NaN  1.91            NaN
23434     NaN    NaN    NaN  1.91            NaN
23435     NaN    NaN    NaN  1.91            NaN
23436     NaN    NaN    NaN  1.91            NaN
23437     NaN    NaN    NaN  1.91            NaN
23438     NaN    NaN    NaN  1.91            NaN
23439     NaN    NaN    NaN  1.91            NaN
23440     NaN    NaN    NaN  1.91            NaN
23441     NaN    NaN    NaN  1.91            NaN
23442     NaN    NaN    NaN  1.91            NaN
23443     NaN    NaN    NaN  1.91            NaN
23444     NaN    NaN    NaN  1.91            NaN
23445     NaN    NaN    NaN  1.92            NaN
23446     NaN    NaN    NaN  1.92            NaN
23447     NaN    NaN    NaN  1.92            NaN
23448     NaN    NaN    NaN  1.92            NaN
23449     NaN    NaN    NaN  1.91            NaN
23450     NaN    NaN    NaN  1.91            NaN
23451     NaN    NaN    NaN  1.92            NaN
23452     NaN    NaN    NaN  1.92            NaN
23453     NaN    NaN    NaN  1.92            NaN
23454     NaN    NaN    NaN  1.92            NaN

[23455 rows x 13 columns]

In [34]:
result.to_csv('FRED_Merged.csv')